on:
  push:
    branches:
      - main
  pull_request: ~
jobs:
  pr_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: bundle exec fastlane mac dev